Get-AppxPackage *3DBuilder* -AllUsers | Remove-AppxPackage
Get-AppxPackage *Candy* -AllUsers | Remove-AppxPackage
Get-AppxPackage Microsoft.XboxApp -AllUsers | Remove-AppxPackage
Get-AppxPackage Microsoft.WindowsMaps -AllUsers | Remove-AppxPackage
Get-AppxPackage *Office* -AllUsers | Remove-AppxPackage
Get-AppxPackage *XboxIdentityProvider -AllUsers | Remove-AppxPackage
Get-AppxPackage *Bing* -AllUsers | Remove-AppxPackage
Get-AppxPackage *Phone -AllUsers | Remove-AppxPackage
Get-AppxPackage *SolitaireCollection -AllUsers | Remove-AppxPackage
Get-AppxPackage *People -AllUsers | Remove-AppxPackage
Get-AppxPackage *Twitter -AllUsers | Remove-AppxPackage
Get-AppxPackage *Zune* -AllUsers | Remove-AppxPackage
Get-AppxPackage *Getstarted -AllUsers | Remove-AppxPackage
Get-AppxPackage *SkypeApp -AllUsers | Remove-AppxPackage
Get-AppxPackage *Facebook* -AllUsers | Remove-AppxPackage
Get-AppxPackage *Netflix -AllUsers | Remove-AppxPackage
Get-AppxPackage *Wunderlist -AllUsers | Remove-AppxPackage
Get-AppxPackage *Duolingo* -AllUsers | Remove-AppxPackage
Get-AppxPackage *EclipseManager -AllUsers | Remove-AppxPackage
Get-AppxPackage Flipboard.Flipboard -AllUsers | Remove-AppxPackage
Get-AppxPackage Microsoft.NetworkSpeedTest -AllUsers | Remove-AppxPackage
Get-AppxPackage *PicsArt-PhotoStudio -AllUsers | Remove-AppxPackage
Get-AppxPackage Microsoft.FreshPaint -AllUsers | Remove-AppxPackage
Get-AppxPackage *Snapfish -AllUsers | Remove-AppxPackage
