Get-AppxPackage *3DBuilder* | Remove-AppxPackage
Get-AppxPackage *Candy* | Remove-AppxPackage
Get-AppxPackage Microsoft.XboxApp | Remove-AppxPackage
Get-AppxPackage Microsoft.WindowsMaps | Remove-AppxPackage
Get-AppxPackage *Office* | Remove-AppxPackage
Get-AppxPackage *XboxIdentityProvider | Remove-AppxPackage
Get-AppxPackage *Bing* | Remove-AppxPackage
Get-AppxPackage *Phone | Remove-AppxPackage
Get-AppxPackage *SolitaireCollection | Remove-AppxPackage
Get-AppxPackage *People | Remove-AppxPackage
Get-AppxPackage *Twitter | Remove-AppxPackage
Get-AppxPackage *Zune* | Remove-AppxPackage
Get-AppxPackage *Getstarted | Remove-AppxPackage
Get-AppxPackage *SkypeApp | Remove-AppxPackage